### ISSUE TITLE
Лабораторная работа №4

### ISSUE THREAD

**Issue by evgerher** [evgerher/Make#1]
Работу выполнил
Сорокин Евгений
@evgeny-p

**Comment by evgeny-p** [comment]
1. В `.gitignore` нет шаблона для игнорирования исполняемого файла.
1. Как следствие, результат сбоки был закоммичен в репозиторий, а этого быть не должно.
1. Сборка недостаточно автоматизирована. Аналогичная проблема встречалась здесь: https://github.com/MforMAD/trpo4/issues/1
1. В заголовочном файле отсутствуют `include guards`.
1. Обычно файл исходного кода и соответствующий ему заголовочный файл имеют одинаковое базовое имя и отличаются только расширением.
1. В файл с реализацией также нужно подключать соответствующий ему заголовочный файл.
1. Сложная для понимания функция `int random()`:
  1. По сигнатуре функции можно предположить, что она возвращает случайное целое число. По факту она всегда возвращает 0.
  1. Также не очень удачным решением является смешивание в функции вычислений и вывода. Такие функции плохо поддаются покрытию юнит-тестами.

Стилистические замечания, исправлять не обязательно:

1. В сообщении мерж-коммита фигурирует номер версии. Обычно для этих целей используются теги.
1. Заголовки двух последних коммитов в ветке начинаются с маленькой буквы. Заголовок первого коммита слишком длинный. Касательно оформлений длинных сообщений см. руководство [How to Write a Git Commit Message: 1. Separate subject from body with a blank line](http://chris.beams.io/posts/git-commit/#separate). В данном конкретном случае имеет место слишком много изменений в одном коммите: и добавление модуля, и добавление сообщений в `main.c`. По крайней мере, это указано в заголовке коммита. По факту `main.c` в этом коммите не менялся, т.е. заголовок коммита не соответствует содержанию.

PS
Если будет желание, можете написать вывод массива с использованием запятой в качестве разделителя элементов. Ожидается, что после последнего элемента запятой не будет.

**Comment by evgerher** [comment]
Исправил все пункты кроме 6, я не могу понять в чем ошибка.
@evgeny-p

**Comment by evgeny-p** [comment]
1. Приложение не компилируется: слишком буквально было воспринято замечание об отсутствии [include guards](https://ru.wikipedia.org/wiki/Include_guard).

1. Касательно шестого пункта. Пусть есть следующие файлы:
  * `rand.h` — содержит объявления и определения, доступные для пользователя.
  * `rand.c` — содержит реализацию функций.
  * `main.c` — использует объявления из `rand.h`.

  В этом случае файл `rand.h` должен быть включен как в `main.c`, так и в `rand.c`. В данном конкретном случае польза может быть неочевидна, т. к. в `rand.c` нет необходимости использовать типы и константы из заголовочного файла за их отсутствием. Проблема может проявить себя при изменении сигнатуры функции в `rand.c`. Если сигнатура в определении функции изменится, но в `rand.c` не будет подключен `rand.h`, и объявление в `rand.h` останется без изменений, то `rand.c` скомпилируется без ошибок. Проблема будет обнаружена только на этапе выполнения программы.

  Для наглядности можете посмотреть пример: https://github.com/evgeny-p/print-number.

  На теге [quiet](https://github.com/evgeny-p/print-number/releases/tag/quiet) приложение компилируется, но ведет себя некорректно.

  На теге [error](https://github.com/evgeny-p/print-number/releases/tag/error) после подключения заголовочного файла компиляция завершается с ошибкой, и несоответствие сигнатур обнаруживается значительно раньше (до этапа выполнения программы).

1. Не обратил внимания при первом ревью: компилировать все-таки нужно с опцией `-Wall`, и при компиляции не должно быть предупреждений.

На что следует обратить внимание, но исправлять не обязательно:

1. > Modify gitignore & rename header file

  Хороший заголовок коммита. И еще по нему видно, что в коммите два независимых изменения. Следовательно, их стоило оформить как два коммита. Это же замечание применимо и к некоторым другим коммитам в ветке.

1. Вынесение создания каталогов в правила — хорошо. Возможен еще такой вариант:
  1. Создать цель dirs, в которой создавать все необходимые каталоги.
  1. Указать эту цель в качестве первой зависимости для `./bin/random`.

  Естественно, делать это не обязательно.

1. Вопрос про разделение элементов последовательности запятой оказался с подвохом.
  ```
  for (i = 0; i < 10; i++) {
      printf("%d", random_s(50));
      if (i < 9)
          printf(",");
  }
  ```
  Размещение внутри цикла условия, которое выполняется практически всегда — неоптимально. Помещение в цикл условия, которое не выполняется практически никогда — тоже. Аналогично с условием, которое выполняется ровно в 50% случаев, если итерации, где условие выполняется и не выполняется, чередуются. Подробности касательно последнего можно искать по ключевым словам «branch prediction».

  В данном конкреном случае задачу обычно решают следующим образом:
  1. За циклом обрабатывается первый элемент. Разделитель не ставится.
  1. В цикле выводится сначала разделитель (относящийся к уже обработанному элементу, а затем следующий элемент.
  Примеры реализации можно найти здесь:
    * glib, функция [g_strjoinv](https://github.com/GNOME/glib/blob/f87e002313d566dcce71a9aba040d22ddb5c1e80/glib/gstrfuncs.c#L2546):
      * В строке 2572 выполняется обработка первого элемента.
      * В следующем за ней цикле сначала в результирующую строку помещается разделитель, затем очередной элемент.
    * [`boost::algorithm::string::join`](http://www.boost.org/doc/libs/1_50_0/boost/algorithm/string/join.hpp). Фрагмент кода, отвечающий за обработку первого элемента, отмечен комментарием `// Append first element`. После него — цикл, аналогичный предыдущему примеру.

**Comment by evgerher** [comment]
Исправлено
Насчет вопроса с подвохом - почитаю отдельно, убрал условие, чтобы не позориться)
@evgeny-p

**Comment by evgeny-p** [comment]
Принято.
